service: dhs-code-assessment-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 60
  memorySize: 2048
  stage: v1
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rekognition:CompareFaces
      Resource: "*"

functions:
  info:
    name: raidLoot
    handler: handler.raidLoot
    events:
      - http:
          path: "/raidLoot"
          method: get
          cors: true

  compare_list:
    name: submitBet
    handler: handler.submitBet
    events:
      - http:
          path: "/submitBet"
          method: post
          cors: true
  